version: '3.0'

services:
  axonserver:
    image: axoniq/axonserver:latest
    container_name: axon-server-container
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - axondata:/data
      - axonevent:/eventdata
      - axonconfig:/config
        
    networks:
      - axon-server

volumes:
  axondata:
  axonevent:
  axonconfig:

networks:
  axon-server:     
