server:
  port: 8083

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  application:
    name: PAYMENT-SERVICE
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
  datasource:
    username: mohammad
    password: 1234
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/paymentdb;AUTO_SERVER=true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


axon:
  eventhandling:
    processors:
      transaction-group:
        mode: subscribing