server:
  port: 8082
spring:
  application:
    name: USER-SERVICE
  datasource:
    username: mohammad
    password: 1234
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/userdb;AUTO_SERVER=true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  main:
    allow-circular-references: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


axon:
  eventhandling:
    processors:
      product-group:
        mode: subscribing